title: "CFC - Synthèse fonctionnelle des composants pour Moodle"
tagline: ""
base_url: ""
logo: ""
favicon: ""

author: "Christian Amauger"

languages: ["fr"]
default_lang: "fr"
language_names:
  fr: "Français"
year: 2025
